### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by songw-zju** [PRBonn/segcontrast#1]
Thanks for your great work! I really like this paper and try to reproduce it recently. When I loaded the pretrained weights you provided, I found that the output of the projection head was 128 channels, not the 20 channels of the semantickitti dataset. I wonder if there is a problem with the provided weights of the  projection head.

**Comment by nuneslu** [comment]
Hi @songw-zju, the pretrained weights have indeed 128 channels due to the projection head that is used during pretraining, that is why we have separated weights `lastepoch199_model_head` and `lastepoch199_model`. To train for semantic segmentation you should load the backbone weights, i.e., `lastepoch199_model`, and use a segmentation head with 20 channels instead of the one used for pretraining ([here](https://github.com/PRBonn/segcontrast/blob/dc9681eab6e84da21023bf99030f3f353aa3cb21/downstream_train.py#L74)):
```py
model = get_model(args, type)
model_head = get_classifier_head(args, type)
```

**Comment by songw-zju** [comment]
Thank you very much for your prompt reply!  That is to say, the projection weights provided here cannot be directly used for semantic segmentation inference and I need to retrain with backbone and segmentation head. I understand this right?

**Comment by nuneslu** [comment]
Exactly, with the pretrained weights it is necessary to train for semantic segmentation. But I will update now the links and also provide the semantic segmentation weights with 100% of labels.

**Comment by songw-zju** [comment]
Thanks for your kind consideration!

**Comment by nuneslu** [comment]
> Thanks for your kind consideration!

It's now available.
