### ISSUE TITLE
Is it feasible to apply this method to the Semantic3D dataset?

### ISSUE THREAD

**Issue by volare1996** [PRBonn/segcontrast#5]
Hi:

     Is it feasible to apply this method to the Semantic3D dataset?

 Best!

**Comment by nuneslu** [comment]
Hi,

We haven't tried but it should be feasible.

For fine-tuning, the weights pre-trained on SemanticKITTI (available in the repo) can be directly used to fine-tune the network to Semantic3D.

The pre-training should work but may be necessary to do some adjustments on the [RANSAC](https://github.com/PRBonn/segcontrast/blob/4d76e41f274f9109f83983b704e748717f204e78/pcd_utils/pcd_preprocess.py#L62) parameters (for ground removal) and on the [DBSCAN](https://github.com/PRBonn/segcontrast/blob/4d76e41f274f9109f83983b704e748717f204e78/pcd_utils/pcd_preprocess.py#L47) (to cluster and segment the remaining objects), since these parameters were tuned for SemanticKITTI dataset.

**Comment by nuneslu** [comment]
I will close this issue due to inactivity, feel free to reopen it if necessary.
